### ISSUE TITLE
Support for #[async_trait(?Send)]

### ISSUE THREAD

**Issue by Hau-Hau** [Neo-Ciber94/mediator-rs#2]
Hi, first I wanted to thank you for great library!

I wondering if it is possible to use #[async_trait(?Send)] with asynchronous handlers.

I think it could be useful because in current state there is no way e.g. to use asynchronous wasm-bindgen bindings which are not implement Send because of how wasm works.

If it is possible and I just miss something then could I please you for example how to achieve that?

Best regards!

**Comment by Neo-Ciber94** [comment]
@Hau-Hau sadly right now is not possible to use async handlers that way, they require to be Send to be registered in the [AsyncMediator](https://github.com/Neo-Ciber94/mediator-rs/blob/dbb619422678d0304203a2df94aee5449b30ba69/mediator/src/default_impls/async_mediator_impl.rs#L910)
