### ISSUE TITLE
its's production ready

### ISSUE THREAD

**Issue by l-7-l** [Neo-Ciber94/mediator-rs#3]
thanks for your suuuuuuuuuper great work. 

i am new to backend programming,  i want to confirm it is ready for distributed system?

**Comment by Neo-Ciber94** [comment]
> thanks for your suuuuuuuuuper great work.
> 
> i am new to backend programming, i want to confirm it is ready for distributed system?

Thanks,

The library hasn't been tested in a distributed environment. 

But `mediator-rs` only provides a layer for sending and receiving messages/events, so should work fine in a distributed system.

**Comment by l-7-l** [comment]
@Neo-Ciber94 Thank you, maybe I'll test it
